In [1]:
import numpy as np
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
import numpy as np
arr = np.random.random((5,5))
arr=(arr - np.mean(arr)) / np.std(arr)
print(arr)

[[-1.79477149  1.13495633 -0.98323261 -0.56871237 -1.15222974]
 [-1.49756191  0.43323756  0.30249146  1.27917054  0.30966786]
 [-0.49648427  0.05256963  1.18676502  1.51587334 -1.31328226]
 [ 0.7350594   0.46924418  1.60233744 -0.88277048 -0.05693616]
 [-0.16313662  0.34952488 -0.24485013 -1.44931679  1.23238718]]


In [9]:
import numpy as np
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


C:\Users\kashy\AppData\Local\Temp\ipykernel_28740\2215623864.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


In [13]:
import numpy as np
arr=np.ones((5,3))
arr1=np.array([[1,2],[3,4],[5,6]])
result=arr@arr1
print(result)

[[ 9. 12.]
 [ 9. 12.]
 [ 9. 12.]
 [ 9. 12.]
 [ 9. 12.]]


In [14]:
import numpy as np
z= np.arange(12).reshape(3,4)
z[(3<z)&(z<=8)]*=-1
print(z)

[[ 0  1  2  3]
 [-4 -5 -6 -7]
 [-8  9 10 11]]


In [15]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [16]:
import numpy as np
Z=np.array([1,2,3])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [17]:
import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\kashy\AppData\Local\Temp\ipykernel_28740\1110915717.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\kashy\AppData\Local\Temp\ipykernel_28740\1110915717.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\kashy\AppData\Local\Temp\ipykernel_28740\1110915717.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [18]:
import numpy as np

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -1.  -9.   3.  -2. -10.   6.   7.   4.   3.  -3.]


In [19]:
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 2 3 4]


In [21]:
import numpy as np

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (2111606757.py, line 10)

In [22]:
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\kashy\AppData\Local\Temp\ipykernel_28740\3084084354.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [25]:
import numpy as np
yesterday=np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)
today=np.datetime64('today', 'D')
print(today)
tommorrow=np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tommorrow)

2026-05-18
2026-05-19
2026-05-20


In [27]:
import numpy as np
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [30]:
import numpy as np
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
print(f"A: {A}, B: {B}, C: {C}")
np.add(A, B,out=B)
np.divide(A,2,out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(f"A: {A}, B: {B}, C: {C}")


A: [1. 1. 1.], B: [2. 2. 2.], C: [3. 3. 3.]
A: [-1.5 -1.5 -1.5], B: [3. 3. 3.], C: [3. 3. 3.]


In [31]:
import numpy as np
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[4. 9. 4. 1. 8. 8. 2. 3. 9. 5.]
[4. 9. 4. 1. 8. 8. 2. 3. 9. 5.]
[4. 9. 4. 1. 8. 8. 2. 3. 9. 5.]
[4 9 4 1 8 8 2 3 9 5]
[4. 9. 4. 1. 8. 8. 2. 3. 9. 5.]


In [33]:
import numpy as np
z=np.zeros((5,5))
z+=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [34]:
import numpy as np
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [36]:
import numpy as np
z=np.linspace(0,1,11,endpoint=False)[1:]
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [37]:
import numpy as np
Z = np.random.random(10)
Z.sort()
print(Z)

[0.01827307 0.30199313 0.34693864 0.36005871 0.42177707 0.64680805
 0.70581146 0.76530489 0.91829507 0.99292634]
