In [2]:
import numpy as np


In [4]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr.shape

(2, 3)

In [7]:
arr_anyno=np.full([3,3],5)
arr_anyno

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [8]:
np.empty((2,3))

array([[3.47739835e-081, 9.99988867e-321, 0.00000000e+000],
       [9.81914907e-312, 0.00000000e+000, 7.56571287e-307]])

In [9]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.logspace(0,2,3)

array([  1.,  10., 100.])

In [13]:
np.random.rand(3)

array([0.71099181, 0.27534645, 0.33313751])

In [14]:
np.random.randn(3)

array([-0.60586698,  0.21155067,  1.41327221])

In [18]:
np.random.randint(0,10,size=3)

array([9, 1, 3])

In [20]:
np.random.uniform(0,10,size=3)

array([3.08667994, 8.71288922, 3.37875445])

In [21]:
np.random.choice([10,20,30])

20

In [28]:
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr.T)

(2, 3)
2
6
int32
4
24
[[1 4]
 [2 5]
 [3 6]]


In [30]:
np.random.seed(42)
a=np.random.randint(0,10,size=(5,3))
a

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [32]:
a.flatten()
a.ravel()

array([6, 3, 7, 4, 6, 9, 2, 6, 7, 4, 3, 7, 7, 2, 5])

In [33]:
a

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [38]:
#a.transpose()
a.swapaxes(0,1)

array([[6, 4, 2, 4, 7],
       [3, 6, 6, 3, 2],
       [7, 9, 7, 7, 5]])

In [36]:
a

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [ ]:
np.sum(a)
np.median(a)
np.mean(a)
np.std(a)
np.var(a)
print(a.max(axis=1))
a.argmin()
np.percentile(a,95)
np.quantile(a,0.9)
np.unique(a)


[7 9 7 7 7]


(array([2, 3, 4, 5, 6, 7, 9]), array([2, 2, 2, 1, 3, 4, 1], dtype=int64))

In [63]:
import time
import numpy as np

py_list = list(range(1000000))
np_array = np.arange(1000000)

start = time.time()
result = [x * 2 for x in py_list]
print("List:", time.time() - start)

start = time.time()
result = np_array * 2
print("Array:", time.time() - start)

List: 0.046137094497680664
Array: 0.007225990295410156


In [64]:
import numpy as np

np.random.seed(42)
student_ids = np.arange(1, 201)
attendance = np.clip(np.random.normal(85, 10, 200), 50, 100).round(1)
study_hours = np.clip(np.random.normal(4, 2, 200), 0, 10).round(1)
assignments_completed = np.random.randint(0, 11, 200)
noise = np.random.normal(0, 8, 200)

marks = np.clip(
    40 + attendance * 0.3 + study_hours * 4 + assignments_completed * 1.5 + noise,
    0, 100
).round(1)