In [2]:
import numpy as np


In [3]:
import numpy as np
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep3179274605568
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


In [4]:
import numpy as np
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
z=np.zeros((10,10))
print(z.nbytes)
print("%d bytes" % (z.size * z.itemsize))


800
800 bytes


In [7]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

Exception: File `'`python'` not found.

In [8]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
import numpy as np
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
import numpy as np
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [14]:
import numpy as np
z=np.arange(9).reshape(3,3)
print("Original Array:\n", z)

Original Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
import numpy as np
z=np.array([1,2,0,0,4,0])
print("Non-zero elements of the array:", np.nonzero(z))

Non-zero elements of the array: (array([0, 1, 4], dtype=int64),)


In [17]:
import numpy as np
z=np.eye(3)
print("Identity Matrix:\n", z)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
import numpy as np
z=np.random.random((3,3,3))
print("Random Array:\n", z)

Random Array:
 [[[0.67642268 0.18997763 0.7063812 ]
  [0.17905559 0.44886734 0.40763391]
  [0.22882184 0.91451744 0.34275576]]

 [[0.66424727 0.84557133 0.88534046]
  [0.88811782 0.72755851 0.46507406]
  [0.69303273 0.64022276 0.24778562]]

 [[0.10416293 0.74772057 0.84051434]
  [0.02856772 0.66956336 0.34907564]
  [0.22266398 0.1552377  0.40118908]]]


In [20]:
import numpy as np
z=np.random.random((10,10))
print(z)
print("minimum:", z.min())
print("maximum:", z.max()) 

[[0.06920408 0.31904211 0.40304841 0.91026374 0.70213435 0.37074099
  0.27414064 0.52812291 0.33699956 0.44256438]
 [0.72439413 0.25233886 0.52898572 0.87074306 0.17877721 0.0700397
  0.48599286 0.67855294 0.66308072 0.31053709]
 [0.58171378 0.01357954 0.40374176 0.01573815 0.20380691 0.051857
  0.11177152 0.08717879 0.6642509  0.80914602]
 [0.46194484 0.70779647 0.98730794 0.43401092 0.73692908 0.81337561
  0.85962385 0.05811787 0.63174457 0.92546647]
 [0.9927528  0.25985295 0.73761791 0.60694538 0.23189895 0.03639373
  0.15671567 0.36118558 0.8163778  0.37628094]
 [0.75189243 0.10303183 0.91713426 0.2306871  0.00975671 0.92511172
  0.65204716 0.55295179 0.74063621 0.37926732]
 [0.94715072 0.36098167 0.64871051 0.11781915 0.27319958 0.73941553
  0.37717118 0.78065318 0.0120351  0.18638952]
 [0.90497464 0.69827471 0.85600293 0.58908441 0.63886866 0.40232399
  0.35365385 0.56106938 0.86299776 0.30905086]
 [0.40631164 0.78832592 0.86800343 0.71715367 0.49662078 0.46083148
  0.79217208 0.

In [21]:
import numpy as np
z=np.random.random(30)
print("mean:", z.mean())

mean: 0.46255587867161535


In [22]:
import numpy as np
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
import numpy as np
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [24]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [27]:
import numpy as np
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [28]:
import numpy as np
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
import numpy as np
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
